version: "3.5"

services:
  web:
    build: './docker/php-nginx/'
    working_dir: /app
    ports:
      - 83:80
    depends_on:
      - database
    volumes:
      - .:/app:cached
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:8.0
    volumes:
      - ./docker/mysqlconf:/etc/mysql/conf.d
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: voisin
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8083:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
